//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_InteractionType
    {
        public ABB_InteractionType()
        {
            this.ABB_CallLog = new HashSet<ABB_CallLog>();
        }
    
        public int Id { get; set; }
        public System.Guid OrgId { get; set; }
        public string Type { get; set; }
        public Nullable<int> IconClass { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ICollection<ABB_CallLog> ABB_CallLog { get; set; }
        public virtual FavIcons FavIcons { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
