//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_Company_Doc_folder_file
    {
        public long Id { get; set; }
        public System.Guid OrgId { get; set; }
        public long FolderId { get; set; }
        public string Name { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string FileType { get; set; }
        public string IconClass { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkASDelete { get; set; }
    
        public virtual ABB_Company_Doc_folder ABB_Company_Doc_folder { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
