//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_Company
    {
        public ABB_Company()
        {
            this.ABB_Appoinment = new HashSet<ABB_Appoinment>();
            this.ABB_CompanyBoardMembers = new HashSet<ABB_CompanyBoardMembers>();
            this.ABB_Company_Doc_folder = new HashSet<ABB_Company_Doc_folder>();
            this.ABB_CompanyAccount = new HashSet<ABB_CompanyAccount>();
            this.ABB_CompanyManDateAssigned = new HashSet<ABB_CompanyManDateAssigned>();
            this.ABB_CompanyManagmentTeam_Staff = new HashSet<ABB_CompanyManagmentTeam_Staff>();
            this.ABB_RequestFinance = new HashSet<ABB_RequestFinance>();
            this.ABB_CompanyShareHolders = new HashSet<ABB_CompanyShareHolders>();
        }
    
        public long Id { get; set; }
        public System.Guid OrgId { get; set; }
        public string CRNo { get; set; }
        public string TradeLicense { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public string EnglishName { get; set; }
        public string ArabicName { get; set; }
        public string Lattitude { get; set; }
        public string Longitude { get; set; }
        public string OfficeAddress { get; set; }
        public int BusinessTypeId { get; set; }
        public int BusinessSectorId { get; set; }
        public System.DateTime TradeLicenseExpiry { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> PortletclassId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ICollection<ABB_Appoinment> ABB_Appoinment { get; set; }
        public virtual ABB_BusinessSector ABB_BusinessSector { get; set; }
        public virtual ICollection<ABB_CompanyBoardMembers> ABB_CompanyBoardMembers { get; set; }
        public virtual ABB_TypeOfBusiness ABB_TypeOfBusiness { get; set; }
        public virtual ICollection<ABB_Company_Doc_folder> ABB_Company_Doc_folder { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Portletclass Portletclass { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ABB_CompanyAccount> ABB_CompanyAccount { get; set; }
        public virtual ICollection<ABB_CompanyManDateAssigned> ABB_CompanyManDateAssigned { get; set; }
        public virtual ICollection<ABB_CompanyManagmentTeam_Staff> ABB_CompanyManagmentTeam_Staff { get; set; }
        public virtual ICollection<ABB_RequestFinance> ABB_RequestFinance { get; set; }
        public virtual ICollection<ABB_CompanyShareHolders> ABB_CompanyShareHolders { get; set; }
    }
}
