//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_CompanyManagmentTeam_Staff
    {
        public ABB_CompanyManagmentTeam_Staff()
        {
            this.ABB_CompanyManDateAssigned = new HashSet<ABB_CompanyManDateAssigned>();
        }
    
        public long Id { get; set; }
        public System.Guid OrgId { get; set; }
        public long CompanyId { get; set; }
        public string FIrstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int JobTitleId { get; set; }
        public string RPNumber { get; set; }
        public System.DateTime RPExpiry { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime Passportexpiry { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ABB_Company ABB_Company { get; set; }
        public virtual ICollection<ABB_CompanyManDateAssigned> ABB_CompanyManDateAssigned { get; set; }
        public virtual ABB_JobTitle ABB_JobTitle { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
