//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_Products
    {
        public ABB_Products()
        {
            this.ABB_RequestFinance = new HashSet<ABB_RequestFinance>();
        }
    
        public long Id { get; set; }
        public System.Guid OrgId { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ABB_RequestFinance> ABB_RequestFinance { get; set; }
    }
}
