//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_RequestFinance
    {
        public long Id { get; set; }
        public System.Guid OrgId { get; set; }
        public long CompanyId { get; set; }
        public long ProductId { get; set; }
        public string Purpose { get; set; }
        public System.DateTime RequiredOn { get; set; }
        public string Tenure { get; set; }
        public decimal Amount { get; set; }
        public string PaymentDetails { get; set; }
        public Nullable<int> CallLogId { get; set; }
        public Nullable<int> DealSatageId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ABB_CallLog ABB_CallLog { get; set; }
        public virtual ABB_Company ABB_Company { get; set; }
        public virtual ABB_DealStages ABB_DealStages { get; set; }
        public virtual ABB_Products ABB_Products { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
