//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_CallLog
    {
        public ABB_CallLog()
        {
            this.ABB_CallLogActionPoint = new HashSet<ABB_CallLogActionPoint>();
            this.ABB_CallLogAttendees = new HashSet<ABB_CallLogAttendees>();
            this.ABB_CallLogGeneralDiscussion = new HashSet<ABB_CallLogGeneralDiscussion>();
            this.ABB_RequestFinance = new HashSet<ABB_RequestFinance>();
        }
    
        public int Id { get; set; }
        public System.Guid OrgId { get; set; }
        public long CompanyId { get; set; }
        public string Subject { get; set; }
        public int InteractionTypeId { get; set; }
        public string MeetingDuration { get; set; }
        public string PlaceOfMeeting { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public string PlannedTime { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string MeetingTime { get; set; }
        public string Description { get; set; }
        public string MarketWatch { get; set; }
        public string NewBusinessOpportunities { get; set; }
        public string ManagementNews { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ABB_InteractionType ABB_InteractionType { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ABB_CallLogActionPoint> ABB_CallLogActionPoint { get; set; }
        public virtual ICollection<ABB_CallLogAttendees> ABB_CallLogAttendees { get; set; }
        public virtual ICollection<ABB_CallLogGeneralDiscussion> ABB_CallLogGeneralDiscussion { get; set; }
        public virtual ICollection<ABB_RequestFinance> ABB_RequestFinance { get; set; }
    }
}
