//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_Company_Doc_folder
    {
        public ABB_Company_Doc_folder()
        {
            this.ABB_Company_Doc_folder_file = new HashSet<ABB_Company_Doc_folder_file>();
        }
    
        public long Id { get; set; }
        public System.Guid OrgId { get; set; }
        public long CompanyId { get; set; }
        public string FolderName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ABB_Company ABB_Company { get; set; }
        public virtual ICollection<ABB_Company_Doc_folder_file> ABB_Company_Doc_folder_file { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
