//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABB_CompanyManDateAssigned
    {
        public int Id { get; set; }
        public System.Guid OrgId { get; set; }
        public long CompanyId { get; set; }
        public int AccountId { get; set; }
        public long StaffId { get; set; }
        public int AssetId { get; set; }
        public int ChannelId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal FromValue { get; set; }
        public decimal ToValue { get; set; }
        public int JoinTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ABB_Company ABB_Company { get; set; }
        public virtual ABB_CompanyAccount ABB_CompanyAccount { get; set; }
        public virtual ABB_CompanyAssets ABB_CompanyAssets { get; set; }
        public virtual ABB_CompanyManagmentTeam_Staff ABB_CompanyManagmentTeam_Staff { get; set; }
        public virtual ABB_JoinType ABB_JoinType { get; set; }
        public virtual ABB_MandateChannel ABB_MandateChannel { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
