//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public Campaigns()
        {
            this.CampaignProducts = new HashSet<CampaignProducts>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public System.Guid CampaignBankTypeId { get; set; }
        public System.Guid CampaignTypeId { get; set; }
        public string CampaignName { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<System.Guid> CampaignOwner { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual CampaignBankTypes CampaignBankTypes { get; set; }
        public virtual ICollection<CampaignProducts> CampaignProducts { get; set; }
        public virtual CampaignTypes CampaignTypes { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
