//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignMedias
    {
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public System.Guid CampaignId { get; set; }
        public string MediaName { get; set; }
        public System.Guid MediaSourceId { get; set; }
        public string FilePath { get; set; }
        public string Narration { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual MediaSources MediaSources { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
