//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseManagment_Task
    {
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public System.Guid CaseId { get; set; }
        public string TaskTitle { get; set; }
        public Nullable<System.Guid> WhoisResponsible { get; set; }
        public System.DateTime TaskDueDate { get; set; }
        public Nullable<System.Guid> TaskCategory { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual CaseManagments CaseManagments { get; set; }
        public virtual CaseManagment_TaskCategory CaseManagment_TaskCategory { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
    }
}
