//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseManagments
    {
        public CaseManagments()
        {
            this.CaseManagment_Followers = new HashSet<CaseManagment_Followers>();
            this.CaseManagment_Note = new HashSet<CaseManagment_Note>();
            this.CaseManagment_SLA = new HashSet<CaseManagment_SLA>();
            this.CaseManagment_Task = new HashSet<CaseManagment_Task>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public Nullable<System.Guid> PersonLeadId { get; set; }
        public string Title { get; set; }
        public string CustomerName { get; set; }
        public string AccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public System.Guid CaseOrgin { get; set; }
        public System.Guid Type { get; set; }
        public Nullable<System.Guid> Priority { get; set; }
        public Nullable<System.Guid> CaseOwner { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> CaseStatus { get; set; }
        public Nullable<System.Guid> CaseManagmentStageId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual CaseManagment_CaseOrgin CaseManagment_CaseOrgin { get; set; }
        public virtual ICollection<CaseManagment_Followers> CaseManagment_Followers { get; set; }
        public virtual ICollection<CaseManagment_Note> CaseManagment_Note { get; set; }
        public virtual CaseManagment_Priority CaseManagment_Priority { get; set; }
        public virtual ICollection<CaseManagment_SLA> CaseManagment_SLA { get; set; }
        public virtual CaseManagment_Status CaseManagment_Status { get; set; }
        public virtual ICollection<CaseManagment_Task> CaseManagment_Task { get; set; }
        public virtual CaseManagment_Type CaseManagment_Type { get; set; }
        public virtual CaseManagmentStageNames CaseManagmentStageNames { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual PersonLeads PersonLeads { get; set; }
        public virtual Users Users { get; set; }
    }
}
