//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCustomerAppoinment_followers
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public int AppoinmentId { get; set; }
        public int FollowerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual CompanyCustomerAppoinment CompanyCustomerAppoinment { get; set; }
    }
}
