//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCustomerAppoinment
    {
        public CompanyCustomerAppoinment()
        {
            this.CompanyCustomerAppoinment_followers = new HashSet<CompanyCustomerAppoinment_followers>();
            this.CompanyCustomerAppoinment_Notification = new HashSet<CompanyCustomerAppoinment_Notification>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> OrgId { get; set; }
        public Nullable<System.Guid> PersonLeadId { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public System.DateTime FromDate_time { get; set; }
        public System.DateTime ToDate_time { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public Nullable<bool> Repeat { get; set; }
        public string RepeatDays { get; set; }
        public Nullable<bool> NOEnddate { get; set; }
        public string Timezone { get; set; }
        public Nullable<bool> AddVideoCall { get; set; }
        public string Location { get; set; }
        public string EventColor { get; set; }
        public string Description { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<bool> Appoinmentstatus { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> appStatus { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<bool> MarkAsDelete { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual ICollection<CompanyCustomerAppoinment_followers> CompanyCustomerAppoinment_followers { get; set; }
        public virtual ICollection<CompanyCustomerAppoinment_Notification> CompanyCustomerAppoinment_Notification { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual PersonLeads PersonLeads { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
    }
}
