//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCustomerAppoinment_NotificationType
    {
        public CompanyCustomerAppoinment_NotificationType()
        {
            this.CompanyCustomerAppoinment_Notification = new HashSet<CompanyCustomerAppoinment_Notification>();
        }
    
        public int Id { get; set; }
        public int OrgId { get; set; }
        public string NotificationName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual ICollection<CompanyCustomerAppoinment_Notification> CompanyCustomerAppoinment_Notification { get; set; }
    }
}
