//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreSettings
    {
        public int Id { get; set; }
        public Nullable<int> AutoLogoutTime { get; set; }
        public Nullable<int> SessionExpireTime { get; set; }
        public Nullable<bool> IsMultiLanguage { get; set; }
        public Nullable<byte> LoginType { get; set; }
        public Nullable<bool> IsSessionSignOffWithUser { get; set; }
        public Nullable<bool> IsIpBaseLock { get; set; }
        public Nullable<bool> IsMultiLogin { get; set; }
        public Nullable<bool> IsSessionExpire { get; set; }
        public Nullable<int> NoOfPasswordHistroy { get; set; }
        public Nullable<byte> SmtpType { get; set; }
        public string SmtpUsername { get; set; }
        public string SmtpPassword { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public Nullable<int> PasswordExpiry { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
