//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealStageNames
    {
        public DealStageNames()
        {
            this.DealStageQuestions = new HashSet<DealStageQuestions>();
            this.PersonLeads = new HashSet<PersonLeads>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public System.Guid PipeLineId { get; set; }
        public string DealQuestionTitle { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Name { get; set; }
        public bool Isvisible { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual Organizations Organizations { get; set; }
        public virtual PipeLines PipeLines { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<DealStageQuestions> DealStageQuestions { get; set; }
        public virtual ICollection<PersonLeads> PersonLeads { get; set; }
    }
}
