//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeQueue
    {
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public System.Guid EmpId { get; set; }
        public System.DateTime Createdate { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
