//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrameworkEntities : DbContext
    {
        public FrameworkEntities()
            : base("name=FrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABB_AccountTypes> ABB_AccountTypes { get; set; }
        public virtual DbSet<ABB_ActivityTypes> ABB_ActivityTypes { get; set; }
        public virtual DbSet<ABB_Appoinment> ABB_Appoinment { get; set; }
        public virtual DbSet<ABB_BusinessSector> ABB_BusinessSector { get; set; }
        public virtual DbSet<ABB_CallLog> ABB_CallLog { get; set; }
        public virtual DbSet<ABB_CallLogActionPoint> ABB_CallLogActionPoint { get; set; }
        public virtual DbSet<ABB_CallLogAttendees> ABB_CallLogAttendees { get; set; }
        public virtual DbSet<ABB_CallLogGeneralDiscussion> ABB_CallLogGeneralDiscussion { get; set; }
        public virtual DbSet<ABB_Company> ABB_Company { get; set; }
        public virtual DbSet<ABB_Company_Doc_folder> ABB_Company_Doc_folder { get; set; }
        public virtual DbSet<ABB_Company_Doc_folder_file> ABB_Company_Doc_folder_file { get; set; }
        public virtual DbSet<ABB_CompanyAccount> ABB_CompanyAccount { get; set; }
        public virtual DbSet<ABB_CompanyAssets> ABB_CompanyAssets { get; set; }
        public virtual DbSet<ABB_CompanyAssetType> ABB_CompanyAssetType { get; set; }
        public virtual DbSet<ABB_CompanyBoardMembers> ABB_CompanyBoardMembers { get; set; }
        public virtual DbSet<ABB_CompanyManagmentTeam_Staff> ABB_CompanyManagmentTeam_Staff { get; set; }
        public virtual DbSet<ABB_CompanyManDateAssigned> ABB_CompanyManDateAssigned { get; set; }
        public virtual DbSet<ABB_CompanyShareHolders> ABB_CompanyShareHolders { get; set; }
        public virtual DbSet<ABB_DealStages> ABB_DealStages { get; set; }
        public virtual DbSet<ABB_InteractionType> ABB_InteractionType { get; set; }
        public virtual DbSet<ABB_JobTitle> ABB_JobTitle { get; set; }
        public virtual DbSet<ABB_JoinType> ABB_JoinType { get; set; }
        public virtual DbSet<ABB_MandateAuthentication> ABB_MandateAuthentication { get; set; }
        public virtual DbSet<ABB_MandateChannel> ABB_MandateChannel { get; set; }
        public virtual DbSet<ABB_MandateChannelType> ABB_MandateChannelType { get; set; }
        public virtual DbSet<ABB_PipeLine> ABB_PipeLine { get; set; }
        public virtual DbSet<ABB_Products> ABB_Products { get; set; }
        public virtual DbSet<ABB_RequestFinance> ABB_RequestFinance { get; set; }
        public virtual DbSet<ABB_TimeLine> ABB_TimeLine { get; set; }
        public virtual DbSet<ABB_TypeOfBusiness> ABB_TypeOfBusiness { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<AssignRoletoUsers> AssignRoletoUsers { get; set; }
        public virtual DbSet<Attendances> Attendances { get; set; }
        public virtual DbSet<CampaignBankTypes> CampaignBankTypes { get; set; }
        public virtual DbSet<CampaignMedias> CampaignMedias { get; set; }
        public virtual DbSet<CampaignProductDocuments> CampaignProductDocuments { get; set; }
        public virtual DbSet<CampaignProducts> CampaignProducts { get; set; }
        public virtual DbSet<Campaigns> Campaigns { get; set; }
        public virtual DbSet<CampaignTypes> CampaignTypes { get; set; }
        public virtual DbSet<CaseManagment_CaseOrgin> CaseManagment_CaseOrgin { get; set; }
        public virtual DbSet<CaseManagment_Followers> CaseManagment_Followers { get; set; }
        public virtual DbSet<CaseManagment_Note> CaseManagment_Note { get; set; }
        public virtual DbSet<CaseManagment_Note_Attachment> CaseManagment_Note_Attachment { get; set; }
        public virtual DbSet<CaseManagment_Note_Comment> CaseManagment_Note_Comment { get; set; }
        public virtual DbSet<CaseManagment_Note_Followers> CaseManagment_Note_Followers { get; set; }
        public virtual DbSet<CaseManagment_Priority> CaseManagment_Priority { get; set; }
        public virtual DbSet<CaseManagment_SLA> CaseManagment_SLA { get; set; }
        public virtual DbSet<CaseManagment_sla_responseName> CaseManagment_sla_responseName { get; set; }
        public virtual DbSet<CaseManagment_Status> CaseManagment_Status { get; set; }
        public virtual DbSet<CaseManagment_Task> CaseManagment_Task { get; set; }
        public virtual DbSet<CaseManagment_TaskCategory> CaseManagment_TaskCategory { get; set; }
        public virtual DbSet<CaseManagment_Type> CaseManagment_Type { get; set; }
        public virtual DbSet<CaseManagments> CaseManagments { get; set; }
        public virtual DbSet<CaseManagmentStageNames> CaseManagmentStageNames { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Commision_AgentBankDetails> Commision_AgentBankDetails { get; set; }
        public virtual DbSet<Commision_CommisionType> Commision_CommisionType { get; set; }
        public virtual DbSet<Commision_ProductCommision> Commision_ProductCommision { get; set; }
        public virtual DbSet<Commision_SalesAgentRules> Commision_SalesAgentRules { get; set; }
        public virtual DbSet<CompanyCustomerAppoinment> CompanyCustomerAppoinment { get; set; }
        public virtual DbSet<CompanyCustomerAppoinment_followers> CompanyCustomerAppoinment_followers { get; set; }
        public virtual DbSet<CompanyCustomerAppoinment_Notification> CompanyCustomerAppoinment_Notification { get; set; }
        public virtual DbSet<CompanyCustomerAppoinment_NotificationType> CompanyCustomerAppoinment_NotificationType { get; set; }
        public virtual DbSet<CompanyCustomerAppoinment_TimeType> CompanyCustomerAppoinment_TimeType { get; set; }
        public virtual DbSet<CompanyModes> CompanyModes { get; set; }
        public virtual DbSet<CoreSettings> CoreSettings { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<DealStageAnswers> DealStageAnswers { get; set; }
        public virtual DbSet<DealStageNames> DealStageNames { get; set; }
        public virtual DbSet<DealStageQuestionModes> DealStageQuestionModes { get; set; }
        public virtual DbSet<DealStageQuestions> DealStageQuestions { get; set; }
        public virtual DbSet<DealStageQuestionTypes> DealStageQuestionTypes { get; set; }
        public virtual DbSet<DealStageQuestionValues> DealStageQuestionValues { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Designations> Designations { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<EmployeeQueue> EmployeeQueue { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<FavIcons> FavIcons { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<HtmlControlNames> HtmlControlNames { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<MediaSources> MediaSources { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Occupation> Occupation { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Person_Company> Person_Company { get; set; }
        public virtual DbSet<Person_Mode> Person_Mode { get; set; }
        public virtual DbSet<PersonLeadNotes> PersonLeadNotes { get; set; }
        public virtual DbSet<PersonLeadProducts> PersonLeadProducts { get; set; }
        public virtual DbSet<PersonLeads> PersonLeads { get; set; }
        public virtual DbSet<PipeLines> PipeLines { get; set; }
        public virtual DbSet<Portletclass> Portletclass { get; set; }
        public virtual DbSet<RoleAssignedModules> RoleAssignedModules { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Salutations> Salutations { get; set; }
        public virtual DbSet<State_Provience_County> State_Provience_County { get; set; }
        public virtual DbSet<SurveyMasters> SurveyMasters { get; set; }
        public virtual DbSet<SurveyQuestions> SurveyQuestions { get; set; }
        public virtual DbSet<SurveyQuestionValues> SurveyQuestionValues { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<TGoal_FinancialPeriod> TGoal_FinancialPeriod { get; set; }
        public virtual DbSet<TGoal_Goal> TGoal_Goal { get; set; }
        public virtual DbSet<TGoal_GoalAgentDetails> TGoal_GoalAgentDetails { get; set; }
        public virtual DbSet<TGoal_GoalLevel> TGoal_GoalLevel { get; set; }
        public virtual DbSet<TGoal_GoalOrganisationDetails> TGoal_GoalOrganisationDetails { get; set; }
        public virtual DbSet<TGoal_GoalProductDetails> TGoal_GoalProductDetails { get; set; }
        public virtual DbSet<TGoal_GoalRuleConfiguration> TGoal_GoalRuleConfiguration { get; set; }
        public virtual DbSet<TGoal_GoalTeamDetails> TGoal_GoalTeamDetails { get; set; }
        public virtual DbSet<TGoal_MetricType> TGoal_MetricType { get; set; }
        public virtual DbSet<TGoal_Organization> TGoal_Organization { get; set; }
        public virtual DbSet<TimeLine> TimeLine { get; set; }
        public virtual DbSet<UserPasswordHistories> UserPasswordHistories { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSessions> UserSessions { get; set; }
    }
}
