//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Company
    {
        public Person_Company()
        {
            this.People = new HashSet<People>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> CompanyMode { get; set; }
        public System.Guid CountryId { get; set; }
        public System.Guid StateId { get; set; }
        public System.Guid CityId { get; set; }
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual CompanyModes CompanyModes { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual ICollection<People> People { get; set; }
        public virtual State_Provience_County State_Provience_County { get; set; }
        public virtual Users Users { get; set; }
    }
}
