//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLeads
    {
        public PersonLeads()
        {
            this.CaseManagments = new HashSet<CaseManagments>();
            this.CompanyCustomerAppoinment = new HashSet<CompanyCustomerAppoinment>();
            this.DealStageAnswers = new HashSet<DealStageAnswers>();
            this.PersonLeadNotes = new HashSet<PersonLeadNotes>();
            this.PersonLeadProducts = new HashSet<PersonLeadProducts>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid DealStageNameId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> CurrentLiablility { get; set; }
        public Nullable<decimal> MonthlyInstallment { get; set; }
        public Nullable<decimal> ExpectedValue { get; set; }
        public Nullable<decimal> SanctionedValue { get; set; }
        public Nullable<decimal> ActualValue { get; set; }
        public Nullable<System.DateTime> ExpectedClosingDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<System.Guid> Assignedto { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ICollection<CaseManagments> CaseManagments { get; set; }
        public virtual ICollection<CompanyCustomerAppoinment> CompanyCustomerAppoinment { get; set; }
        public virtual ICollection<DealStageAnswers> DealStageAnswers { get; set; }
        public virtual DealStageNames DealStageNames { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual People People { get; set; }
        public virtual ICollection<PersonLeadNotes> PersonLeadNotes { get; set; }
        public virtual ICollection<PersonLeadProducts> PersonLeadProducts { get; set; }
        public virtual Users Users { get; set; }
    }
}
