//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portletclass
    {
        public Portletclass()
        {
            this.ABB_Company = new HashSet<ABB_Company>();
        }
    
        public int Id { get; set; }
        public System.Guid OrgId { get; set; }
        public string Name { get; set; }
        public string portletTitleclass { get; set; }
        public string CaptionFontclass { get; set; }
        public string captionIconClass { get; set; }
        public string CaptionSubjectclass { get; set; }
        public string CaptionHelperClass { get; set; }
        public string btnAddclass { get; set; }
        public string btndeleteclass { get; set; }
        public string btneditclass { get; set; }
        public string btnsubmitclass { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ICollection<ABB_Company> ABB_Company { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
