//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.AssignRoletoUsers = new HashSet<AssignRoletoUsers>();
            this.RoleAssignedModules = new HashSet<RoleAssignedModules>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> OrgId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<AssignRoletoUsers> AssignRoletoUsers { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual ICollection<RoleAssignedModules> RoleAssignedModules { get; set; }
    }
}
