//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public Teams()
        {
            this.Commision_AgentBankDetails = new HashSet<Commision_AgentBankDetails>();
            this.Commision_ProductCommision = new HashSet<Commision_ProductCommision>();
            this.Commision_SalesAgentRules = new HashSet<Commision_SalesAgentRules>();
            this.Employees = new HashSet<Employees>();
            this.TGoal_GoalTeamDetails = new HashSet<TGoal_GoalTeamDetails>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrgId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ICollection<Commision_AgentBankDetails> Commision_AgentBankDetails { get; set; }
        public virtual ICollection<Commision_ProductCommision> Commision_ProductCommision { get; set; }
        public virtual ICollection<Commision_SalesAgentRules> Commision_SalesAgentRules { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<TGoal_GoalTeamDetails> TGoal_GoalTeamDetails { get; set; }
    }
}
