//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGoal_GoalRuleConfiguration
    {
        public TGoal_GoalRuleConfiguration()
        {
            this.TGoal_GoalAgentDetails = new HashSet<TGoal_GoalAgentDetails>();
            this.TGoal_GoalOrganisationDetails = new HashSet<TGoal_GoalOrganisationDetails>();
            this.TGoal_GoalProductDetails = new HashSet<TGoal_GoalProductDetails>();
            this.TGoal_GoalTeamDetails = new HashSet<TGoal_GoalTeamDetails>();
        }
    
        public int Id { get; set; }
        public System.Guid OrgId { get; set; }
        public int GoalId { get; set; }
        public int FinancialPeriodId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual Organizations Organizations { get; set; }
        public virtual TGoal_FinancialPeriod TGoal_FinancialPeriod { get; set; }
        public virtual TGoal_Goal TGoal_Goal { get; set; }
        public virtual ICollection<TGoal_GoalAgentDetails> TGoal_GoalAgentDetails { get; set; }
        public virtual ICollection<TGoal_GoalOrganisationDetails> TGoal_GoalOrganisationDetails { get; set; }
        public virtual ICollection<TGoal_GoalProductDetails> TGoal_GoalProductDetails { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<TGoal_GoalTeamDetails> TGoal_GoalTeamDetails { get; set; }
    }
}
