//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGoal_Goal
    {
        public TGoal_Goal()
        {
            this.TGoal_GoalRuleConfiguration = new HashSet<TGoal_GoalRuleConfiguration>();
        }
    
        public int Id { get; set; }
        public System.Guid OrgId { get; set; }
        public string GoalName { get; set; }
        public int GoalLevelId { get; set; }
        public int MetricTypeId { get; set; }
        public string Value { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual Organizations Organizations { get; set; }
        public virtual TGoal_GoalLevel TGoal_GoalLevel { get; set; }
        public virtual TGoal_MetricType TGoal_MetricType { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<TGoal_GoalRuleConfiguration> TGoal_GoalRuleConfiguration { get; set; }
    }
}
