//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSessions
    {
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SessionInfo { get; set; }
        public string SessionCode { get; set; }
        public System.DateTime SessionActiveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
