//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.ABB_AccountTypes = new HashSet<ABB_AccountTypes>();
            this.ABB_ActivityTypes = new HashSet<ABB_ActivityTypes>();
            this.ABB_Appoinment = new HashSet<ABB_Appoinment>();
            this.ABB_Appoinment1 = new HashSet<ABB_Appoinment>();
            this.ABB_Appoinment2 = new HashSet<ABB_Appoinment>();
            this.ABB_BusinessSector = new HashSet<ABB_BusinessSector>();
            this.ABB_CallLog = new HashSet<ABB_CallLog>();
            this.ABB_CallLogActionPoint = new HashSet<ABB_CallLogActionPoint>();
            this.ABB_CallLogAttendees = new HashSet<ABB_CallLogAttendees>();
            this.ABB_CallLogAttendees1 = new HashSet<ABB_CallLogAttendees>();
            this.ABB_CallLogGeneralDiscussion = new HashSet<ABB_CallLogGeneralDiscussion>();
            this.ABB_Company = new HashSet<ABB_Company>();
            this.ABB_Company_Doc_folder = new HashSet<ABB_Company_Doc_folder>();
            this.ABB_Company_Doc_folder_file = new HashSet<ABB_Company_Doc_folder_file>();
            this.ABB_CompanyAccount = new HashSet<ABB_CompanyAccount>();
            this.ABB_CompanyAssets = new HashSet<ABB_CompanyAssets>();
            this.ABB_CompanyAssetType = new HashSet<ABB_CompanyAssetType>();
            this.ABB_CompanyBoardMembers = new HashSet<ABB_CompanyBoardMembers>();
            this.ABB_CompanyManagmentTeam_Staff = new HashSet<ABB_CompanyManagmentTeam_Staff>();
            this.ABB_CompanyManDateAssigned = new HashSet<ABB_CompanyManDateAssigned>();
            this.ABB_CompanyShareHolders = new HashSet<ABB_CompanyShareHolders>();
            this.ABB_DealStages = new HashSet<ABB_DealStages>();
            this.ABB_InteractionType = new HashSet<ABB_InteractionType>();
            this.ABB_JobTitle = new HashSet<ABB_JobTitle>();
            this.ABB_JoinType = new HashSet<ABB_JoinType>();
            this.ABB_MandateAuthentication = new HashSet<ABB_MandateAuthentication>();
            this.ABB_MandateChannel = new HashSet<ABB_MandateChannel>();
            this.ABB_MandateChannelType = new HashSet<ABB_MandateChannelType>();
            this.ABB_PipeLine = new HashSet<ABB_PipeLine>();
            this.ABB_Products = new HashSet<ABB_Products>();
            this.ABB_RequestFinance = new HashSet<ABB_RequestFinance>();
            this.ABB_TimeLine = new HashSet<ABB_TimeLine>();
            this.AssignRoletoUsers = new HashSet<AssignRoletoUsers>();
            this.Attendances = new HashSet<Attendances>();
            this.Attendances1 = new HashSet<Attendances>();
            this.CampaignBankTypes = new HashSet<CampaignBankTypes>();
            this.CampaignMedias = new HashSet<CampaignMedias>();
            this.CampaignProductDocuments = new HashSet<CampaignProductDocuments>();
            this.CampaignProducts = new HashSet<CampaignProducts>();
            this.Campaigns = new HashSet<Campaigns>();
            this.CampaignTypes = new HashSet<CampaignTypes>();
            this.CaseManagment_CaseOrgin = new HashSet<CaseManagment_CaseOrgin>();
            this.CaseManagment_Followers = new HashSet<CaseManagment_Followers>();
            this.CaseManagment_Note = new HashSet<CaseManagment_Note>();
            this.CaseManagment_Note_Attachment = new HashSet<CaseManagment_Note_Attachment>();
            this.CaseManagment_Note_Comment = new HashSet<CaseManagment_Note_Comment>();
            this.CaseManagment_Note_Followers = new HashSet<CaseManagment_Note_Followers>();
            this.CaseManagment_Priority = new HashSet<CaseManagment_Priority>();
            this.CaseManagment_SLA = new HashSet<CaseManagment_SLA>();
            this.CaseManagment_sla_responseName = new HashSet<CaseManagment_sla_responseName>();
            this.CaseManagment_Status = new HashSet<CaseManagment_Status>();
            this.CaseManagment_Task = new HashSet<CaseManagment_Task>();
            this.CaseManagment_TaskCategory = new HashSet<CaseManagment_TaskCategory>();
            this.CaseManagment_Type = new HashSet<CaseManagment_Type>();
            this.CaseManagments = new HashSet<CaseManagments>();
            this.CaseManagmentStageNames = new HashSet<CaseManagmentStageNames>();
            this.Cities = new HashSet<Cities>();
            this.Commision_AgentBankDetails = new HashSet<Commision_AgentBankDetails>();
            this.Commision_AgentBankDetails1 = new HashSet<Commision_AgentBankDetails>();
            this.Commision_CommisionType = new HashSet<Commision_CommisionType>();
            this.Commision_ProductCommision = new HashSet<Commision_ProductCommision>();
            this.Commision_SalesAgentRules = new HashSet<Commision_SalesAgentRules>();
            this.Commision_SalesAgentRules1 = new HashSet<Commision_SalesAgentRules>();
            this.CompanyCustomerAppoinment = new HashSet<CompanyCustomerAppoinment>();
            this.CompanyCustomerAppoinment1 = new HashSet<CompanyCustomerAppoinment>();
            this.CompanyCustomerAppoinment2 = new HashSet<CompanyCustomerAppoinment>();
            this.CompanyModes = new HashSet<CompanyModes>();
            this.CoreSettings = new HashSet<CoreSettings>();
            this.Countries = new HashSet<Countries>();
            this.DealStageAnswers = new HashSet<DealStageAnswers>();
            this.DealStageNames = new HashSet<DealStageNames>();
            this.DealStageQuestionModes = new HashSet<DealStageQuestionModes>();
            this.DealStageQuestions = new HashSet<DealStageQuestions>();
            this.DealStageQuestionTypes = new HashSet<DealStageQuestionTypes>();
            this.DealStageQuestionValues = new HashSet<DealStageQuestionValues>();
            this.Departments = new HashSet<Departments>();
            this.Designations = new HashSet<Designations>();
            this.Documents = new HashSet<Documents>();
            this.Employees = new HashSet<Employees>();
            this.Employees1 = new HashSet<Employees>();
            this.FavIcons = new HashSet<FavIcons>();
            this.Genders = new HashSet<Genders>();
            this.HtmlControlNames = new HashSet<HtmlControlNames>();
            this.Languages = new HashSet<Languages>();
            this.Locations = new HashSet<Locations>();
            this.Logs = new HashSet<Logs>();
            this.MediaSources = new HashSet<MediaSources>();
            this.Notifications = new HashSet<Notifications>();
            this.Occupation = new HashSet<Occupation>();
            this.People = new HashSet<People>();
            this.Person_Company = new HashSet<Person_Company>();
            this.Person_Mode = new HashSet<Person_Mode>();
            this.PersonLeadNotes = new HashSet<PersonLeadNotes>();
            this.PersonLeadProducts = new HashSet<PersonLeadProducts>();
            this.PersonLeads = new HashSet<PersonLeads>();
            this.PipeLines = new HashSet<PipeLines>();
            this.Salutations = new HashSet<Salutations>();
            this.State_Provience_County = new HashSet<State_Provience_County>();
            this.SurveyMasters = new HashSet<SurveyMasters>();
            this.SurveyQuestions = new HashSet<SurveyQuestions>();
            this.SurveyQuestionValues = new HashSet<SurveyQuestionValues>();
            this.Teams = new HashSet<Teams>();
            this.TGoal_FinancialPeriod = new HashSet<TGoal_FinancialPeriod>();
            this.TGoal_Goal = new HashSet<TGoal_Goal>();
            this.TGoal_GoalAgentDetails = new HashSet<TGoal_GoalAgentDetails>();
            this.TGoal_GoalAgentDetails1 = new HashSet<TGoal_GoalAgentDetails>();
            this.TGoal_GoalLevel = new HashSet<TGoal_GoalLevel>();
            this.TGoal_GoalOrganisationDetails = new HashSet<TGoal_GoalOrganisationDetails>();
            this.TGoal_GoalProductDetails = new HashSet<TGoal_GoalProductDetails>();
            this.TGoal_GoalRuleConfiguration = new HashSet<TGoal_GoalRuleConfiguration>();
            this.TGoal_GoalTeamDetails = new HashSet<TGoal_GoalTeamDetails>();
            this.TGoal_MetricType = new HashSet<TGoal_MetricType>();
            this.TGoal_Organization = new HashSet<TGoal_Organization>();
            this.TimeLine = new HashSet<TimeLine>();
            this.UserPasswordHistories = new HashSet<UserPasswordHistories>();
            this.UserSessions = new HashSet<UserSessions>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> OrgId { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public Nullable<System.Guid> Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string OfficeEmail { get; set; }
        public string Password { get; set; }
        public Nullable<int> PasswordExpiry { get; set; }
        public Nullable<System.DateTime> LastPasswordChanged { get; set; }
        public string Salt { get; set; }
        public Nullable<int> SessionExpireTime { get; set; }
        public Nullable<int> MaxNoOfAttempts { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Attempts { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public bool MarkAsDelete { get; set; }
    
        public virtual ICollection<ABB_AccountTypes> ABB_AccountTypes { get; set; }
        public virtual ICollection<ABB_ActivityTypes> ABB_ActivityTypes { get; set; }
        public virtual ICollection<ABB_Appoinment> ABB_Appoinment { get; set; }
        public virtual ICollection<ABB_Appoinment> ABB_Appoinment1 { get; set; }
        public virtual ICollection<ABB_Appoinment> ABB_Appoinment2 { get; set; }
        public virtual ICollection<ABB_BusinessSector> ABB_BusinessSector { get; set; }
        public virtual ICollection<ABB_CallLog> ABB_CallLog { get; set; }
        public virtual ICollection<ABB_CallLogActionPoint> ABB_CallLogActionPoint { get; set; }
        public virtual ICollection<ABB_CallLogAttendees> ABB_CallLogAttendees { get; set; }
        public virtual ICollection<ABB_CallLogAttendees> ABB_CallLogAttendees1 { get; set; }
        public virtual ICollection<ABB_CallLogGeneralDiscussion> ABB_CallLogGeneralDiscussion { get; set; }
        public virtual ICollection<ABB_Company> ABB_Company { get; set; }
        public virtual ICollection<ABB_Company_Doc_folder> ABB_Company_Doc_folder { get; set; }
        public virtual ICollection<ABB_Company_Doc_folder_file> ABB_Company_Doc_folder_file { get; set; }
        public virtual ICollection<ABB_CompanyAccount> ABB_CompanyAccount { get; set; }
        public virtual ICollection<ABB_CompanyAssets> ABB_CompanyAssets { get; set; }
        public virtual ICollection<ABB_CompanyAssetType> ABB_CompanyAssetType { get; set; }
        public virtual ICollection<ABB_CompanyBoardMembers> ABB_CompanyBoardMembers { get; set; }
        public virtual ICollection<ABB_CompanyManagmentTeam_Staff> ABB_CompanyManagmentTeam_Staff { get; set; }
        public virtual ICollection<ABB_CompanyManDateAssigned> ABB_CompanyManDateAssigned { get; set; }
        public virtual ICollection<ABB_CompanyShareHolders> ABB_CompanyShareHolders { get; set; }
        public virtual ICollection<ABB_DealStages> ABB_DealStages { get; set; }
        public virtual ICollection<ABB_InteractionType> ABB_InteractionType { get; set; }
        public virtual ICollection<ABB_JobTitle> ABB_JobTitle { get; set; }
        public virtual ICollection<ABB_JoinType> ABB_JoinType { get; set; }
        public virtual ICollection<ABB_MandateAuthentication> ABB_MandateAuthentication { get; set; }
        public virtual ICollection<ABB_MandateChannel> ABB_MandateChannel { get; set; }
        public virtual ICollection<ABB_MandateChannelType> ABB_MandateChannelType { get; set; }
        public virtual ICollection<ABB_PipeLine> ABB_PipeLine { get; set; }
        public virtual ICollection<ABB_Products> ABB_Products { get; set; }
        public virtual ICollection<ABB_RequestFinance> ABB_RequestFinance { get; set; }
        public virtual ICollection<ABB_TimeLine> ABB_TimeLine { get; set; }
        public virtual ICollection<AssignRoletoUsers> AssignRoletoUsers { get; set; }
        public virtual ICollection<Attendances> Attendances { get; set; }
        public virtual ICollection<Attendances> Attendances1 { get; set; }
        public virtual ICollection<CampaignBankTypes> CampaignBankTypes { get; set; }
        public virtual ICollection<CampaignMedias> CampaignMedias { get; set; }
        public virtual ICollection<CampaignProductDocuments> CampaignProductDocuments { get; set; }
        public virtual ICollection<CampaignProducts> CampaignProducts { get; set; }
        public virtual ICollection<Campaigns> Campaigns { get; set; }
        public virtual ICollection<CampaignTypes> CampaignTypes { get; set; }
        public virtual ICollection<CaseManagment_CaseOrgin> CaseManagment_CaseOrgin { get; set; }
        public virtual ICollection<CaseManagment_Followers> CaseManagment_Followers { get; set; }
        public virtual ICollection<CaseManagment_Note> CaseManagment_Note { get; set; }
        public virtual ICollection<CaseManagment_Note_Attachment> CaseManagment_Note_Attachment { get; set; }
        public virtual ICollection<CaseManagment_Note_Comment> CaseManagment_Note_Comment { get; set; }
        public virtual ICollection<CaseManagment_Note_Followers> CaseManagment_Note_Followers { get; set; }
        public virtual ICollection<CaseManagment_Priority> CaseManagment_Priority { get; set; }
        public virtual ICollection<CaseManagment_SLA> CaseManagment_SLA { get; set; }
        public virtual ICollection<CaseManagment_sla_responseName> CaseManagment_sla_responseName { get; set; }
        public virtual ICollection<CaseManagment_Status> CaseManagment_Status { get; set; }
        public virtual ICollection<CaseManagment_Task> CaseManagment_Task { get; set; }
        public virtual ICollection<CaseManagment_TaskCategory> CaseManagment_TaskCategory { get; set; }
        public virtual ICollection<CaseManagment_Type> CaseManagment_Type { get; set; }
        public virtual ICollection<CaseManagments> CaseManagments { get; set; }
        public virtual ICollection<CaseManagmentStageNames> CaseManagmentStageNames { get; set; }
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual ICollection<Commision_AgentBankDetails> Commision_AgentBankDetails { get; set; }
        public virtual ICollection<Commision_AgentBankDetails> Commision_AgentBankDetails1 { get; set; }
        public virtual ICollection<Commision_CommisionType> Commision_CommisionType { get; set; }
        public virtual ICollection<Commision_ProductCommision> Commision_ProductCommision { get; set; }
        public virtual ICollection<Commision_SalesAgentRules> Commision_SalesAgentRules { get; set; }
        public virtual ICollection<Commision_SalesAgentRules> Commision_SalesAgentRules1 { get; set; }
        public virtual ICollection<CompanyCustomerAppoinment> CompanyCustomerAppoinment { get; set; }
        public virtual ICollection<CompanyCustomerAppoinment> CompanyCustomerAppoinment1 { get; set; }
        public virtual ICollection<CompanyCustomerAppoinment> CompanyCustomerAppoinment2 { get; set; }
        public virtual ICollection<CompanyModes> CompanyModes { get; set; }
        public virtual ICollection<CoreSettings> CoreSettings { get; set; }
        public virtual ICollection<Countries> Countries { get; set; }
        public virtual ICollection<DealStageAnswers> DealStageAnswers { get; set; }
        public virtual ICollection<DealStageNames> DealStageNames { get; set; }
        public virtual ICollection<DealStageQuestionModes> DealStageQuestionModes { get; set; }
        public virtual ICollection<DealStageQuestions> DealStageQuestions { get; set; }
        public virtual ICollection<DealStageQuestionTypes> DealStageQuestionTypes { get; set; }
        public virtual ICollection<DealStageQuestionValues> DealStageQuestionValues { get; set; }
        public virtual ICollection<Departments> Departments { get; set; }
        public virtual ICollection<Designations> Designations { get; set; }
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual ICollection<FavIcons> FavIcons { get; set; }
        public virtual ICollection<Genders> Genders { get; set; }
        public virtual Genders Genders1 { get; set; }
        public virtual ICollection<HtmlControlNames> HtmlControlNames { get; set; }
        public virtual ICollection<Languages> Languages { get; set; }
        public virtual ICollection<Locations> Locations { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual ICollection<MediaSources> MediaSources { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Occupation> Occupation { get; set; }
        public virtual Organizations Organizations { get; set; }
        public virtual ICollection<People> People { get; set; }
        public virtual ICollection<Person_Company> Person_Company { get; set; }
        public virtual ICollection<Person_Mode> Person_Mode { get; set; }
        public virtual ICollection<PersonLeadNotes> PersonLeadNotes { get; set; }
        public virtual ICollection<PersonLeadProducts> PersonLeadProducts { get; set; }
        public virtual ICollection<PersonLeads> PersonLeads { get; set; }
        public virtual ICollection<PipeLines> PipeLines { get; set; }
        public virtual ICollection<Salutations> Salutations { get; set; }
        public virtual ICollection<State_Provience_County> State_Provience_County { get; set; }
        public virtual ICollection<SurveyMasters> SurveyMasters { get; set; }
        public virtual ICollection<SurveyQuestions> SurveyQuestions { get; set; }
        public virtual ICollection<SurveyQuestionValues> SurveyQuestionValues { get; set; }
        public virtual ICollection<Teams> Teams { get; set; }
        public virtual ICollection<TGoal_FinancialPeriod> TGoal_FinancialPeriod { get; set; }
        public virtual ICollection<TGoal_Goal> TGoal_Goal { get; set; }
        public virtual ICollection<TGoal_GoalAgentDetails> TGoal_GoalAgentDetails { get; set; }
        public virtual ICollection<TGoal_GoalAgentDetails> TGoal_GoalAgentDetails1 { get; set; }
        public virtual ICollection<TGoal_GoalLevel> TGoal_GoalLevel { get; set; }
        public virtual ICollection<TGoal_GoalOrganisationDetails> TGoal_GoalOrganisationDetails { get; set; }
        public virtual ICollection<TGoal_GoalProductDetails> TGoal_GoalProductDetails { get; set; }
        public virtual ICollection<TGoal_GoalRuleConfiguration> TGoal_GoalRuleConfiguration { get; set; }
        public virtual ICollection<TGoal_GoalTeamDetails> TGoal_GoalTeamDetails { get; set; }
        public virtual ICollection<TGoal_MetricType> TGoal_MetricType { get; set; }
        public virtual ICollection<TGoal_Organization> TGoal_Organization { get; set; }
        public virtual ICollection<TimeLine> TimeLine { get; set; }
        public virtual ICollection<UserPasswordHistories> UserPasswordHistories { get; set; }
        public virtual ICollection<UserSessions> UserSessions { get; set; }
    }
}
