//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Symbiosis.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string GenearlLogoutBtn {
            get {
                return ResourceManager.GetString("GenearlLogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Connected.
        /// </summary>
        internal static string GenearlStayConnectedBtn {
            get {
                return ResourceManager.GetString("GenearlStayConnectedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        internal static string GeneralMsgLoggedOut {
            get {
                return ResourceManager.GetString("GeneralMsgLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggout Failed, Please try again later..
        /// </summary>
        internal static string GeneralMsgLoggedOutFailed {
            get {
                return ResourceManager.GetString("GeneralMsgLoggedOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, Please try again later.
        /// </summary>
        internal static string GeneralMsgPleaseTryLater {
            get {
                return ResourceManager.GetString("GeneralMsgPleaseTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is about to expire in less then .
        /// </summary>
        internal static string GeneralMsgSessionNotificationBody {
            get {
                return ResourceManager.GetString("GeneralMsgSessionNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout Notification.
        /// </summary>
        internal static string GeneralMsgSessionNotificationTitle {
            get {
                return ResourceManager.GetString("GeneralMsgSessionNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeMainTitle {
            get {
                return ResourceManager.GetString("HomeMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string HomeMainTitle2 {
            get {
                return ResourceManager.GetString("HomeMainTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string IsLeft {
            get {
                return ResourceManager.GetString("IsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To end all current sessions.
        /// </summary>
        internal static string LoginActiveSessionEndWarning {
            get {
                return ResourceManager.GetString("LoginActiveSessionEndWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        internal static string LoginActiveSessionEndWarningBtn {
            get {
                return ResourceManager.GetString("LoginActiveSessionEndWarningBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string LoginChangePassword {
            get {
                return ResourceManager.GetString("LoginChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string LoginChangePassword2 {
            get {
                return ResourceManager.GetString("LoginChangePassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to change your password.
        /// </summary>
        internal static string LoginChangePasswordWarning {
            get {
                return ResourceManager.GetString("LoginChangePasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username and password..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max no of attempts exhausted, Please contact Administrator.
        /// </summary>
        internal static string LoginMaxNoOfAttempts {
            get {
                return ResourceManager.GetString("LoginMaxNoOfAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string LoginNewPassword {
            get {
                return ResourceManager.GetString("LoginNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string LoginNewPassword2 {
            get {
                return ResourceManager.GetString("LoginNewPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password already used, Please use new one.
        /// </summary>
        internal static string LoginPasswordAlreadyUsed {
            get {
                return ResourceManager.GetString("LoginPasswordAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed, Please login.
        /// </summary>
        internal static string LoginPasswordChanged {
            get {
                return ResourceManager.GetString("LoginPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string LoginPasswordRequired {
            get {
                return ResourceManager.GetString("LoginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password &amp; confirm the password.
        /// </summary>
        internal static string LoginPleaseEnterNewPassword {
            get {
                return ResourceManager.GetString("LoginPleaseEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Active Session(s) exist.
        /// </summary>
        internal static string LoginSessionExist {
            get {
                return ResourceManager.GetString("LoginSessionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session terminated, Please login..
        /// </summary>
        internal static string LoginSessionKilled {
            get {
                return ResourceManager.GetString("LoginSessionKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session failed to terminate..
        /// </summary>
        internal static string LoginSessionKilledFailed {
            get {
                return ResourceManager.GetString("LoginSessionKilledFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled, Please contact admin.
        /// </summary>
        internal static string LoginStatusNotEnabled {
            get {
                return ResourceManager.GetString("LoginStatusNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        internal static string LoginTitle2 {
            get {
                return ResourceManager.GetString("LoginTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some on tried to login using you username with incorrect password at .
        /// </summary>
        internal static string LoginTriedToLogin {
            get {
                return ResourceManager.GetString("LoginTriedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect..
        /// </summary>
        internal static string LoginUserDoesNotExist {
            get {
                return ResourceManager.GetString("LoginUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username / password incorrect or disabled..
        /// </summary>
        internal static string LoginUserDoesNotExistOrDisabled {
            get {
                return ResourceManager.GetString("LoginUserDoesNotExistOrDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string LoginUsernameRequired {
            get {
                return ResourceManager.GetString("LoginUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired, please login again..
        /// </summary>
        internal static string LogoutSessionExpired {
            get {
                return ResourceManager.GetString("LogoutSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NotificationTitle2 {
            get {
                return ResourceManager.GetString("NotificationTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized for this module, please conotact admin for access or login with proper authorization.
        /// </summary>
        internal static string PermissionBody {
            get {
                return ResourceManager.GetString("PermissionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout / Login.
        /// </summary>
        internal static string PermissionLogoutBtn {
            get {
                return ResourceManager.GetString("PermissionLogoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string PermissionTitle {
            get {
                return ResourceManager.GetString("PermissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access.
        /// </summary>
        internal static string PermissionTitle2 {
            get {
                return ResourceManager.GetString("PermissionTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home.
        /// </summary>
        internal static string PermissionTryAgainLaterBtn {
            get {
                return ResourceManager.GetString("PermissionTryAgainLaterBtn", resourceCulture);
            }
        }
    }
}
